# variablesの設定
## Github上でsecretsを設定
## Secretsに設定した値は暗号化されて、GITHUB上に安全に保存される
## 登録後に値をまったく確認出来なくなる
## ※コマンドラインでも実行可能 gh secret set PASSWORD --body '保存したいシークレットの値'
name: Secret
on: push
jobs:
  print:
    runs-on: ubuntu-latest                        # ランナー　Ubuntuで実行 (GitHubが用意してくれているVM環境で実行することができる)
    env:
      PASSWORD: ${{ secrets.PASSWORD }}           # secretsに設定した値をEnvに設定
    steps:                                        # ワークフローに置ける最小単位
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # ログ出力はマスクされない（Secretsはログ出力してはいけない！お試し実行）